git clone http://git.enlightenment.org/enlightenment/modules/alarm.git/
git clone http://git.enlightenment.org/enlightenment/modules/comp-scale.git/
git clone http://git.enlightenment.org/enlightenment/modules/cpu.git/
git clone http://git.enlightenment.org/enlightenment/modules/diskio.git/
git clone http://git.enlightenment.org/enlightenment/modules/eenvader.fractal.git/
git clone http://git.enlightenment.org/enlightenment/modules/elev8.git/
git clone http://git.enlightenment.org/enlightenment/modules/elfe.git/
git clone http://git.enlightenment.org/enlightenment/modules/empris.git/
git clone http://git.enlightenment.org/enlightenment/modules/engage.git/
git clone http://git.enlightenment.org/enlightenment/modules/everything-places.git/
git clone http://git.enlightenment.org/enlightenment/modules/everything-websearch.git/
git clone http://git.enlightenment.org/enlightenment/modules/eweather.git/
git clone http://git.enlightenment.org/enlightenment/modules/forecasts.git/
git clone http://git.enlightenment.org/enlightenment/modules/mail.git/
git clone http://git.enlightenment.org/enlightenment/modules/moon.git/
git clone http://git.enlightenment.org/enlightenment/modules/mpdule.git/
git clone http://git.enlightenment.org/enlightenment/modules/net.git/
git clone http://git.enlightenment.org/enlightenment/modules/news.git/
git clone http://git.enlightenment.org/enlightenment/modules/packagekit.git/
git clone http://git.enlightenment.org/enlightenment/modules/penguins.git/
git clone http://git.enlightenment.org/enlightenment/modules/photo.git/
git clone http://git.enlightenment.org/enlightenment/modules/places.git/
git clone http://git.enlightenment.org/enlightenment/modules/tclock.git/
rm -rf ./*/.git
rm -f ./*/.gitignore